「住宅・土地統計調査 平成30年住宅・土地統計調査 住宅及び世帯に関する基本集計 全国・都道府県・市区町村 (44-4)」より、データの前処理演習

In [281]:
import pandas as pd

データが分割されてダウンロードされたので統合する。

In [282]:
df = pd.read_csv('japan_housing\FEH_00200522_240325173037.csv')
df.head()

,地域 コード,地域,時間軸(年次) コード,時間軸(年次),世帯の種類 コード,世帯の種類,住宅の所有の関係 コード,住宅の所有の関係,世帯の年間収入階級 コード,世帯の年間収入階級,/表章項目,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
0,0,全国,2018000000,2018年,0,総数,0,総数,0,総数,NaN,"53,788,000",2.30,4.41,32.78
1,0,全国,2018000000,2018年,0,総数,0,総数,1,100万円未満,NaN,"3,159,000",1.36,3.53,23.83
2,0,全国,2018000000,2018年,0,総数,0,総数,2,100～200万円未満,NaN,"6,529,100",1.57,4.04,27.37
3,0,全国,2018000000,2018年,0,総数,0,総数,4,200～300万円未満,NaN,"8,703,100",1.89,4.31,30.28
4,0,全国,2018000000,2018年,0,総数,0,総数,5,300～400万円未満,NaN,"7,669,500",2.19,4.34,31.53

In [283]:
df.shape

(125000, 15)

In [284]:
df1 = pd.read_csv('japan_housing\FEH_00200522_240325173059.csv')
df1.head()

,地域 コード,地域,時間軸(年次) コード,時間軸(年次),世帯の種類 コード,世帯の種類,住宅の所有の関係 コード,住宅の所有の関係,世帯の年間収入階級 コード,世帯の年間収入階級,/表章項目,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
0,20210,駒ヶ根市,2018000000,2018年,0,総数,23,民営借家,0,総数,NaN,***,***,***,***
1,20210,駒ヶ根市,2018000000,2018年,0,総数,23,民営借家,1,100万円未満,NaN,***,***,***,***
2,20210,駒ヶ根市,2018000000,2018年,0,総数,23,民営借家,2,100～200万円未満,NaN,***,***,***,***
3,20210,駒ヶ根市,2018000000,2018年,0,総数,23,民営借家,4,200～300万円未満,NaN,***,***,***,***
4,20210,駒ヶ根市,2018000000,2018年,0,総数,23,民営借家,5,300～400万円未満,NaN,***,***,***,***

In [285]:
df1.shape

(125000, 15)

In [286]:
df2 = pd.read_csv('japan_housing\FEH_00200522_240325173122.csv')
df2.head()

,地域 コード,地域,時間軸(年次) コード,時間軸(年次),世帯の種類 コード,世帯の種類,住宅の所有の関係 コード,住宅の所有の関係,世帯の年間収入階級 コード,世帯の年間収入階級,/表章項目,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
0,42000,長崎県,2018000000,2018年,1,主世帯,21,公営の借家,0,総数,NaN,"34,200",2.14,3.48,20.94
1,42000,長崎県,2018000000,2018年,1,主世帯,21,公営の借家,1,100万円未満,NaN,"4,600",1.44,3.24,19.44
2,42000,長崎県,2018000000,2018年,1,主世帯,21,公営の借家,2,100～200万円未満,NaN,"10,700",1.79,3.40,20.14
3,42000,長崎県,2018000000,2018年,1,主世帯,21,公営の借家,4,200～300万円未満,NaN,"8,400",2.30,3.60,21.46
4,42000,長崎県,2018000000,2018年,1,主世帯,21,公営の借家,5,300～400万円未満,NaN,"4,100",2.79,3.59,21.99

In [287]:
df2.shape

(25100, 15)

In [288]:
japan_housing = pd.concat([df, df1, df2], axis=0)
japan_housing.head()

,地域 コード,地域,時間軸(年次) コード,時間軸(年次),世帯の種類 コード,世帯の種類,住宅の所有の関係 コード,住宅の所有の関係,世帯の年間収入階級 コード,世帯の年間収入階級,/表章項目,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
0,0,全国,2018000000,2018年,0,総数,0,総数,0,総数,NaN,"53,788,000",2.30,4.41,32.78
1,0,全国,2018000000,2018年,0,総数,0,総数,1,100万円未満,NaN,"3,159,000",1.36,3.53,23.83
2,0,全国,2018000000,2018年,0,総数,0,総数,2,100～200万円未満,NaN,"6,529,100",1.57,4.04,27.37
3,0,全国,2018000000,2018年,0,総数,0,総数,4,200～300万円未満,NaN,"8,703,100",1.89,4.31,30.28
4,0,全国,2018000000,2018年,0,総数,0,総数,5,300～400万円未満,NaN,"7,669,500",2.19,4.34,31.53

In [289]:
#各データ数分読み取れているか確認。行数は275100になるはず。
japan_housing.shape

(275100, 15)

In [290]:
#コードが邪魔な気がするので消す。でも結局質的変数なのには変わらないからいるのだろうか。よくわからないからとりあえず消してみる。
#結局地域コードは中央区とかだと他地方にもありそうなので残すことにした。これでいいのかは分からない。
japan_housing = japan_housing.drop(['時間軸(年次) コード', '時間軸(年次)', '世帯の種類 コード', '住宅の所有の関係 コード', '世帯の年間収入階級 コード', '/表章項目'], axis=1)
japan_housing.head()

,地域 コード,地域,世帯の種類,住宅の所有の関係,世帯の年間収入階級,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
0,0,全国,総数,総数,総数,"53,788,000",2.30,4.41,32.78
1,0,全国,総数,総数,100万円未満,"3,159,000",1.36,3.53,23.83
2,0,全国,総数,総数,100～200万円未満,"6,529,100",1.57,4.04,27.37
3,0,全国,総数,総数,200～300万円未満,"8,703,100",1.89,4.31,30.28
4,0,全国,総数,総数,300～400万円未満,"7,669,500",2.19,4.34,31.53

In [291]:
japan_housing.shape

(275100, 9)

In [292]:
#全国の行数210。(全国＋都道府県)*210=48*210=10080と一致するかどうか。
nationwide_regions = ['全国', '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県', '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県', '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県', '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県', '徳島県', '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県']
filtered_japan_housing = japan_housing[japan_housing['地域'].isin(nationwide_regions)]
filtered_japan_housing.shape

(10080, 9)

In [293]:
japan_housing = japan_housing[~japan_housing['地域'].isin(nationwide_regions)]
japan_housing.head()

,地域 コード,地域,世帯の種類,住宅の所有の関係,世帯の年間収入階級,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
420,1100,札幌市,総数,総数,総数,"924,000",2.05,3.77,29.79
421,1100,札幌市,総数,総数,100万円未満,"52,900",1.27,2.73,19.98
422,1100,札幌市,総数,総数,100～200万円未満,"137,400",1.40,3.16,23.21
423,1100,札幌市,総数,総数,200～300万円未満,"179,800",1.73,3.63,27.64
424,1100,札幌市,総数,総数,300～400万円未満,"140,800",2.03,3.85,29.98

In [294]:
#3つのデータを統合した総行数275100から、全国＋都道府県の行数10080を引いた数265020と一致するかどうか。
japan_housing.shape

(265020, 9)

In [300]:
japan_housing = japan_housing[~japan_housing['世帯の種類'].str.contains('総数')]
japan_housing = japan_housing[~japan_housing['住宅の所有の関係'].str.contains('総数')]
japan_housing = japan_housing[~japan_housing['世帯の年間収入階級'].str.contains('総数')]

In [301]:
japan_housing.shape

(136296, 9)

In [302]:
japan_housing.head()

,地域 コード,地域,世帯の種類,住宅の所有の関係,世帯の年間収入階級,普通世帯数【世帯】,１世帯当たり人員【人】,１世帯当たり居住室数【室】,１世帯当たり居住室の畳数【畳】
501,1100,札幌市,主世帯,持ち家,100万円未満,"13,100",1.44,4.57,34.45
502,1100,札幌市,主世帯,持ち家,100～200万円未満,"46,500",1.57,4.78,36.23
503,1100,札幌市,主世帯,持ち家,200～300万円未満,"84,100",1.96,4.96,38.90
504,1100,札幌市,主世帯,持ち家,300～400万円未満,"71,600",2.25,5.05,40.25
505,1100,札幌市,主世帯,持ち家,400～500万円未満,"55,100",2.60,4.99,40.95

california_housingのデータと似たものを探してとりあえず住宅・土地統計調査からそれらしきものを引っ張ってきてみたがいかんともしがたい。
欲しい気がするデータが散らばっているためマージやら統合やらしないといけなかったのか。
質的変数と量的変数が混ざっていてkmeans法が使えないらしい。
コードに置き換えても結局カテゴリーなのだからあれれ。
Gower距離でクラスタリングする手法があるそうだがよくわからない……。
世帯間の年間収入階級は平均値でもよいのだろうか。

In [297]:
japan_housing.to_csv('japan_housing_cleansing.csv')